apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: button.donwaldhartman.co.za
spec:
  secretName: button.donwaldhartman.co.za
  dnsNames:
    - button.donwaldhartman.co.za
  issuerRef:
    name: letsencrypt-production
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
