apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: donwaldhartman-certificate
spec:
  secretName: donwaldhartman-tls-secret
  dnsNames:
    - button.donwaldhartman.co.za
    - argo.donwaldhartman.co.za
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
