apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@donwaldhartman.co.za
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
      - dns01:
          cloudflare:
            email: donwald.hartman@gmail.com
            apiTokenSecretRef:
              name: cloudflare-secret
              key: cloudflare-token
