---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend
        
spec:


  selector:
    
    app: nginx

  ports:
   - protocol: TCP
     port: 80
  externalIPs:
   - 178.79.160.49 
