---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: backend
        
spec:

  type: ClusterIP
  selector:
    
    app: nginx

  ports:
   
    - port: 32123
      targetPort: 80
