---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    layer: backend
        
spec:
selector:
app: nginx
layer: backend
ports:
- protocol: TCP
  port: 80
externalIPs:
- 178.79.160.49    

