---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    tier: backend
        
spec:
selector:
app: nginx
tier: backend
ports:
- protocol: TCP
  port: 80
externalIPs:
- 178.79.160.49    

