---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: backend
        
spec:

  type: NodePort
  selector:
    
    app: nginx

  ports:
   
    - nodePort: 32123
      port: 80
      targetPort: 80
