---
kind: Service 
apiVersion: v1 
metadata:
  name: nginx
  labels:
    app: nginx
    layer: frontend
        
spec:


  selector:
    
    app: nginx

  ports:
   - protocol: TCP
     port: 80
  externalIPs:
   - 178.79.160.49 
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donwaldhartman-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - secretName: donwaldhartman-tls-secret
      hosts:
        - button.donwaldhartman.co.za
        - argo.donwaldhartman.co.za
  rules:
    - host: button.donwaldhartman.co.za
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  name: http
    - host: argo.donwaldhartman.co.za
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: http
