---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: phpfpm
    layer: backend
spec:
    
  replicas: 6
  selector:
    matchLabels:
      app: phpfpm
  template:
    
    
    metadata:
      labels:
        app: phpfpm
            
    spec:
    
      containers:
      
        - name: phpfpm
          image: bitnami/php-fpm
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/website
              name: contents
          lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "chown -R www-data:www-data /var/website"]                      
      volumes:
        - name: contents
          hostPath:
            path: /var/website
            type: Directory
