---
name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  pre-flight-test:
    name: Pre-Flight Test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Kubernetes resources
        run: |
          cp /etc/kubernetes/admin.conf $HOME/
          chown $(id -u):$(id -g) $HOME/admin.conf
          export KUBECONFIG=$HOME/admin.conf
          kubectl get pods -n nginx
          kubectl get svc -n nginx
  webserver-rollout:
    name: Webserver Rollout
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restart webserver
        run: |
          kubectl rollout restart -n nginx
  reporting:
    name: Generating Report
    runs-on: self-hosted
    steps:
      - name: Creating report
        uses: actions/checkout@v2
      - run: echo 'Content here. You *can* use Markdown.' | tee /tmp/report.md
      - uses: ./
        with:
          name: Report name
          title: Report title here
          body-file: /tmp/report.md
