# A basic workflow for CI using GitHub Actions
name: CI

# Define when the workflow will run
on:
  push:
    # Triggers the workflow on push events to the "master" branch
    branches:
      - master
  workflow_dispatch:
    # Allows you to manually run the workflow from the Actions tab

# Define the jobs to be performed
jobs:
  pre-flight-test:
    name: Pre-Flight Test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test Kubernetes resources
        run: |
          cp /etc/kubernetes/admin.conf $HOME/
          chown $(id -u):$(id -g) $HOME/admin.conf
          export KUBECONFIG=$HOME/admin.conf
          kubectl get pods -n nginx
          kubectl get svc -n nginx
  webserver-rollout:
    name: Webserver Rollout
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restart webserver
        run: |
          kubectl rollout restart -n nginx
  reporting:
    name: Generating Report
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        run: |
          echo 'Content here. You *can* use Markdown.' | tee /tmp/report.md
          # Then use this action to generate the report.
          uses: dtinth/markdown-report-action@v1
          with:
            name: Report name
            title: Report title here
            body-file: /tmp/report.md
