# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kind:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.1.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Testing
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl cluster-info
