---
name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  pre-flight-test:
    name: Pre-Flight Test
    runs-on: self-hosted
    steps:
      - name: Test Kubernetes resources
        run: |
          cp /etc/kubernetes/admin.conf $HOME/
          chown $(id -u):$(id -g) $HOME/admin.conf
          export KUBECONFIG=$HOME/admin.conf
          kubectl get pods -n nginx
          kubectl get svc -n nginx
  webserver-rollout:
    name: Webserver Rollout
    runs-on: self-hosted
    needs: pre-flight-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restart webserver
        run: |
          cp /etc/kubernetes/admin.conf $HOME/
          chown $(id -u):$(id -g) $HOME/admin.conf
          export KUBECONFIG=$HOME/admin.conf
          kubectl rollout restart deployment -n nginx

